#!/usr/bin/env python
"""Check that all plugins have corresponding documentation files.

This script ensures each plugin has a documentation file at:
    docs/en/checks/{plugin-slug}.md

Where plugin-slug is the plugin class name with underscores replaced by dashes.

The help_url is auto-generated by the Plugin base class from the class name,
so this script validates that the documentation file exists.

Usage:
    python scripts/check_plugin_help_urls.py

Exit codes:
    0 - All plugins have documentation files
    1 - One or more plugins are missing documentation
"""

import ast
import sys
from pathlib import Path


# Plugins with external documentation (skip docs check)
EXTERNAL_DOCS_PLUGINS = {
    "try_files_is_evil_too",  # Links to external blog post
}


def plugin_name_to_slug(plugin_name):
    """Convert a plugin class name to a kebab-case URL slug.

    Examples:
        http_splitting -> http-splitting
        ssrf -> ssrf
        add_header_multiline -> add-header-multiline
    """
    return plugin_name.replace("_", "-")


def get_plugin_classes(file_path):
    """
    Parse a Python file and extract plugin class names.

    Args:
        file_path: Path to the plugin Python file.

    Returns:
        List of class names that inherit from Plugin.
    """
    results = []

    try:
        with open(file_path, encoding="utf-8") as f:
            tree = ast.parse(f.read(), filename=str(file_path))
    except SyntaxError as e:
        print(f"  Syntax error in {file_path}: {e}")
        return []

    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue

        # Check if this class inherits from Plugin
        is_plugin = False
        for base in node.bases:
            if isinstance(base, ast.Name) and base.id == "Plugin":
                is_plugin = True
                break

        if not is_plugin:
            continue

        results.append(node.name)

    return results


def check_documentation_exists(plugin_name, docs_dir):
    """
    Check if a plugin has a corresponding documentation file.

    Args:
        plugin_name: Name of the plugin class.
        docs_dir: Path to docs/en/checks directory.

    Returns:
        Tuple of (exists, expected_path).
    """
    slug = plugin_name_to_slug(plugin_name)
    expected_path = docs_dir / f"{slug}.md"
    return expected_path.exists(), expected_path


def main():
    """
    Main function to check all plugin documentation files.

    Returns:
        Exit code (0 for success, 1 for failure).
    """
    project_root = Path(__file__).parent.parent
    plugins_dir = project_root / "gixy" / "plugins"
    docs_dir = project_root / "docs" / "en" / "checks"

    if not plugins_dir.exists():
        print(f"Plugins directory not found: {plugins_dir}")
        return 1

    if not docs_dir.exists():
        print(f"Documentation directory not found: {docs_dir}")
        return 1

    errors = []
    checked = 0
    skipped = 0

    print("Checking plugin documentation files...\n")

    for plugin_file in sorted(plugins_dir.glob("*.py")):
        # Skip __init__.py and base plugin.py
        if plugin_file.name in ("__init__.py", "plugin.py"):
            continue
        # Underscore-prefixed modules are internal data/helper files,
        # not plugins (matches PluginsManager.import_plugins).
        if plugin_file.name.startswith("_"):
            continue

        plugin_classes = get_plugin_classes(plugin_file)

        for class_name in plugin_classes:
            # Skip plugins with external documentation
            if class_name in EXTERNAL_DOCS_PLUGINS:
                skipped += 1
                print(f"  [skip] {class_name}: uses external documentation")
                continue

            checked += 1
            exists, expected_path = check_documentation_exists(class_name, docs_dir)

            if exists:
                slug = plugin_name_to_slug(class_name)
                print(f"  [ok] {class_name}: docs/en/checks/{slug}.md")
            else:
                errors.append((plugin_file.name, class_name, expected_path))
                print(
                    f"  [MISSING] {class_name}: {expected_path.relative_to(project_root)}"
                )

    print(f"\n{'=' * 60}")
    print(f"Checked {checked} plugin(s), skipped {skipped}")

    if errors:
        print(f"\nMissing {len(errors)} documentation file(s):\n")
        for filename, class_name, expected_path in errors:
            slug = plugin_name_to_slug(class_name)
            print(f"  - {class_name} ({filename})")
            print(f"    Expected: docs/en/checks/{slug}.md")
            print()

        print("To fix, create the missing documentation files.")
        print("Each file should have YAML front-matter with title and description.")
        return 1

    print(f"\nAll {checked} plugin(s) have documentation files!")
    return 0


if __name__ == "__main__":
    sys.exit(main())
